import { StyleSheet } from 'react-native';
import { AppPalette } from '../../theme/useAppTheme';

export const createStyles = (colors: AppPalette, insetsTop: number) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    noProviderOverlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 200,
      backgroundColor: colors.background,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
      paddingHorizontal: 32,
    },
    noProviderTitle: {
      fontSize: 20,
      fontWeight: '700' as const,
      color: colors.text,
      marginTop: 16,
      marginBottom: 8,
    },
    noProviderMessage: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
      textAlign: 'center' as const,
      marginBottom: 24,
    },
    noProviderButton: {
      paddingVertical: 12,
      paddingHorizontal: 28,
      borderRadius: 12,
      backgroundColor: colors.primary,
    },
    noProviderButtonText: {
      fontSize: 15,
      fontWeight: '600' as const,
      color: colors.onPrimary,
    },
    topFade: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: insetsTop + 56 + 30,
      zIndex: 99,
    },
    headerContainer: {
      position: 'absolute',
      top: insetsTop,
      left: 0,
      right: 0,
      height: 56,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      zIndex: 100,
    },
    menuButton: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
    },
    selectorWrapper: {
      flex: 1,
      height: '100%',
      justifyContent: 'center',
      paddingLeft: 8,
    },
    content: {
      flex: 1,
    },
    listContent: {
      paddingTop: insetsTop + 56 + 10,
    },
    paginationHeader: {
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingBottom: 8,
    },
    loadMoreButton: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
      backgroundColor: colors.surfaceAlt,
    },
    loadMoreButtonText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    paginationHint: {
      marginTop: 6,
      color: colors.textTertiary,
      fontSize: 12,
    },
    emptyState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    emptyTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '700',
      marginBottom: 8,
    },
    emptyText: {
      color: colors.textSecondary,
      fontSize: 14,
      textAlign: 'center',
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger,
      borderWidth: 1,
      marginHorizontal: 12,
      marginTop: 10,
      marginBottom: 4,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    errorText: {
      color: colors.text,
      fontSize: 12,
      flex: 1,
    },
    exportButton: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center' as const,
      justifyContent: 'center' as const,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.subtleBorder,
      marginLeft: 8,
    },
    exportOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    exportContent: {
      width: '85%',
      maxWidth: 360,
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
    },
    exportHeader: {
      flexDirection: 'row' as const,
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    exportTitle: {
      fontSize: 18,
      fontWeight: '600' as const,
      color: colors.text,
    },
    exportCloseBtn: {
      padding: 4,
    },
    exportSectionLabel: {
      fontSize: 13,
      fontWeight: '500' as const,
      color: colors.textSecondary,
      marginBottom: 8,
      marginTop: 4,
    },
    exportFormatRow: {
      flexDirection: 'row' as const,
      gap: 8,
      marginBottom: 16,
    },
    exportFormatBtn: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center' as const,
    },
    exportFormatBtnActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    exportFormatText: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    exportFormatTextActive: {
      color: colors.primary,
      fontWeight: '600' as const,
    },
    exportCheckRow: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      paddingVertical: 8,
      gap: 10,
    },
    exportCheckBox: {
      width: 22,
      height: 22,
      borderRadius: 5,
      borderWidth: 1.5,
      borderColor: colors.border,
      justifyContent: 'center' as const,
      alignItems: 'center' as const,
    },
    exportCheckBoxActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    exportCheckLabel: {
      fontSize: 14,
      color: colors.text,
    },
    exportActions: {
      flexDirection: 'row' as const,
      justifyContent: 'flex-end',
      gap: 10,
      marginTop: 20,
    },
    exportCancelBtn: {
      paddingVertical: 10,
      paddingHorizontal: 18,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    exportCancelText: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    exportConfirmBtn: {
      paddingVertical: 10,
      paddingHorizontal: 22,
      borderRadius: 10,
      backgroundColor: colors.primary,
    },
    exportConfirmBtnDisabled: {
      opacity: 0.5,
    },
    exportConfirmText: {
      fontSize: 14,
      fontWeight: '600' as const,
      color: colors.onPrimary,
    },
    visionOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    visionContent: {
      width: '85%',
      maxWidth: 360,
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
    },
    visionTitle: {
      fontSize: 17,
      fontWeight: '600' as const,
      color: colors.text,
      marginBottom: 10,
    },
    visionMessage: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
      marginBottom: 20,
    },
    visionActions: {
      gap: 10,
    },
    visionSwitchBtn: {
      paddingVertical: 12,
      borderRadius: 10,
      backgroundColor: colors.primary,
      alignItems: 'center' as const,
    },
    visionSwitchText: {
      fontSize: 15,
      fontWeight: '600' as const,
      color: colors.onPrimary,
    },
    visionContinueBtn: {
      paddingVertical: 12,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center' as const,
    },
    visionContinueText: {
      fontSize: 15,
      color: colors.textSecondary,
    },
    modeModalContent: {
      width: '80%',
      maxWidth: 320,
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
    },
    modeModalTitle: {
      fontSize: 16,
      fontWeight: '600' as const,
      color: colors.text,
      marginBottom: 12,
    },
    modeItem: {
      flexDirection: 'row' as const,
      alignItems: 'center' as const,
      justifyContent: 'space-between' as const,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: 10,
    },
    modeItemActive: {
      backgroundColor: colors.primarySoft,
    },
    modeItemText: {
      fontSize: 15,
      color: colors.text,
      flex: 1,
    },
    modeItemTextActive: {
      fontWeight: '600' as const,
      color: colors.primary,
    },
  });
